/**
 * rent car api
 * rent car api description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarPositionDto } from './carPositionDto';
import { CustomerDetailsDto } from './customerDetailsDto';


export interface CarDetailsDto { 
    id?: string;
    manufacturer: string;
    license: string;
    vin: string;
    rentedBy: CustomerDetailsDto;
    position: CarPositionDto;
}

