FROM node:16-alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN apk add --no-cache tzdata
ENV TZ=Europe/Warsaw

RUN apk add g++ make python3

WORKDIR /app

COPY package*.json ./
RUN npm i

COPY .. .

CMD ["npm", "run", "start:dev"]
