FROM node:16-alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN apk add --no-cache tzdata
ENV TZ=Europe/Warsaw

WORKDIR /opt/app

COPY package*.json ./
RUN npm i

COPY .. .

CMD ["npm", "start"]
